HorrorOnline.UI/Controllers/StoryController.cs
using HorrorOnline.Core.Domain.Entities;
using HorrorOnline.Core.DTO;
using HorrorOnline.Core.ServiceContracts.Stories;
using HorrorOnline.Core.ServiceContracts.Tags;
using HorrorOnline.UI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;

namespace HorrorOnline.UI.Controllers
{
    [Route("[controller]")]
    public class StoryController : Controller
    {
        private readonly IStoryAdderService _storyAdderService;
        private readonly IStoryGetterService _storyGetterService;
        private readonly IStoryDeleterService _storyDeleterService;

        private readonly ITagAdderService _tagAdderService;
        private readonly ITagGetterService _tagGetterService;

        public StoryController(IStoryAdderService storyAdderService, IStoryGetterService storyGetterService, IStoryDeleterService storyDeleterService, ITagAdderService tagAdderService, ITagGetterService tagGetterService)
        {
            _storyAdderService = storyAdderService;
            _storyGetterService = storyGetterService;
            _storyDeleterService = storyDeleterService;

            _tagAdderService = tagAdderService;
            _tagGetterService = tagGetterService;
        }

        [Route("/")]
        [AllowAnonymous]
        public async Task<ActionResult> Index()
        {
            IEnumerable<StoryResponse> stories = await _storyGetterService.GetAllStories();

            return View(stories);
        }

        [Route("[action]/{storyID}")]
        [HttpGet]
        [AllowAnonymous]
        public async Task<ActionResult> Details(Guid storyID)
        {
            StoryResponse? storyToDisplay = await _storyGetterService.GetStoryByID(storyID);

            if (storyToDisplay == null)
                return RedirectToAction("Index");

            return View(storyToDisplay);
        }

        [Route("[action]")]
        [HttpGet]
        [AllowAnonymous]
        public async Task<ActionResult> SearchForm()
        {
            return View();
        }

        [Route("[action]")]
        [HttpGet]
        [AllowAnonymous]
        public async Task<ActionResult> SearchResults(string searchTerm)
        {
            IEnumerable<StoryResponse> stories = await _storyGetterService.GetSelectedStories(searchTerm, nameof(StoryResponse.Title));

            return View(stories);
        }

        [Route("[action]")]
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Route("[action]")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(StoryWithTagsModel storyWithTagsModel)
        {
            if (ModelState.IsValid == false)
            {
                ViewBag.Errors = ModelState.Values.SelectMany(error => error.Errors).Select(error => error.ErrorMessage);

                return View(storyWithTagsModel);
            }

            StoryAddRequest storyAddRequest = new StoryAddRequest()
            {
                Title = storyWithTagsModel.Title,
                Summary = storyWithTagsModel.Summary,
                Text = storyWithTagsModel.Text,
                Tags = await TagParser(storyWithTagsModel.Tags),
                //TODO retrieve author form authentication
                AuthorId = Guid.NewGuid(),
            };

            StoryResponse storyAdded = await _storyAdderService.AddStory(storyAddRequest);


            try
            {
                var storyIDparameter = new { storyID = storyAdded.StoryId };
                return RedirectToAction(nameof(Details), storyIDparameter);
            }
            catch
            {
                return View();
            }
        }

        #region Tag management helpers
        /// <summary>
        /// Retrieves or creates the appropiate tag entities, and returns their ids
        /// </summary>
        /// <param name="tagsString">String containing tags names separated by commas</param>
        /// <returns></returns>
        private async Task<ICollection<TagResponse>?> TagParser(string tagsString)
        {
            if (string.IsNullOrEmpty(tagsString))
                return null;

            List<string> stringTags = tagsString.Split(',').ToList();

            ICollection<TagResponse> returnTags = new List<TagResponse>();
            stringTags.ForEach(async tag =>
            {
                tag.Trim();
                returnTags.Add( await GetOrAddTag(tag) );
            });

            return returnTags;
        }

        private async Task<TagResponse> GetOrAddTag(string tag)
        {
            TagResponse? tagFromGet = await _tagGetterService.GetTagByName(tag);
            if (tagFromGet != null)
                return tagFromGet;

            TagAddRequest tagAddRequest = new TagAddRequest() { TagName = tag };
            return await _tagAdderService.AddTag(tagAddRequest);
        }
        #endregion

        public ActionResult Delete(int id)
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

HorrorOnline.UI/Views/Story/Create.cshtml
@model StoryWithTagsModel
@{
	ViewBag.Title = "Subir relato";
}


<form asp-controller="Story" asp-action="Create" method="post" class="flex wrap gap-16 flex-column align-items-center justify-self-center">

	<h1>Subir relato</h1>

	<div class="flex gap-16 margin-bottom-8 w-stretch">
		<label asp-for="Title"></label>
		<input asp-for="Title" class="w-stretch"></input>
	</div>
	<span asp-validation-for="Title"></span>

	<label asp-for="Summary" ></label>
	<textarea asp-for="Summary" class="margin-bottom-8"></textarea>
	<span asp-validation-for="Summary"></span>

	<label asp-for="Text"></label>
	<textarea asp-for="Text" class="story-text-input margin-bottom-8"></textarea>
	<span asp-validation-for="Text"></span>

	<div class="flex gap-16 margin-bottom-8 w-stretch">
		<label asp-for="Tags"></label>
		<input asp-for="Tags" class="w-stretch"></input>
	</div>
	<span asp-validation-for="Tags"></span>

	<button type="submit" class="base-font text-white">Mandar relato</button>
	@if (ViewBag.Errors != null)
	{
		@foreach (string error in ViewBag.Errors)
		{
			<p style="color:red">@error</p>
		}
	}
</form>

HorrorOnline.UI/Views/Story/Details.cshtml
@model StoryResponse
@{
    ViewData["Title"] = "Leer";
}

@{
    ViewBag.DisplayMode = "full";
}
<partial name="PartialViews/StoryPartialView" model="Model" />

HorrorOnline.UI/Views/Story/Index.cshtml
@model IEnumerable<StoryResponse>
@{
    ViewData["Title"] = "Populares";
}

@if (Model == null || Model.Count() == 0)
{
	<span class="text-message justify-center">No se encontraron relatos.</span>
}
else
{
	@foreach (StoryResponse story in Model)
	{
		<partial name="PartialViews/StoryPartialView" model="story" />
	}
}

HorrorOnline.UI/Views/Story/SearchForm.cshtml
@{
    ViewData["Title"] = "Búsqueda";
}


	<div class="story-card flex flex-column gap-16 justify-self-center search-form align-items-center">
		<h1>Búsqueda</h1>
		<form asp-controller="Story" asp-action="SearchResults" method="get" >
			<div class="flex gap-16">

				@*
					<select id="searchField" class="base-font">
					<option value="title">Título</option>
					<option value="tag">Tag</option>
					<option value="author">Autor</option>
				</select>
				*@
				<input class="base-font" type="search" id="search" name="searchTerm" placeholder="búsqueda"/>
				<button class="flex">
					<img class="search-icon" src="/media/img/magnifying-glass-solid-full.svg" />
				</button>

			</div>
		</form>
	</div>

HorrorOnline.UI/Views/Story/SearchResults.cshtml
@model IEnumerable<StoryResponse>
@{
	ViewData["Title"] = "Resultados de la búsqueda";
}

@if (Model == null || Model.Count() == 0)
{
	<span class="text-message justify-self-center">No se encontraron relatos.</span>
}
else
{
	@foreach (StoryResponse story in Model)
	{
		<partial name="PartialViews/StoryPartialView" model="story" />
	}
}